export const countryLimits = [
  { country: "Afghanistan", limit: 0.0 },
  { country: "Albania", limit: 0.01 },
  { country: "Algeria", limit: 0.1 },
  { country: "Andorra", limit: 0.05 },
  { country: "Angola", limit: 0.06 },
  { country: "Antigua and Barbuda", limit: 0.08 },
  { country: "Argentina", limit: 0.05 },
  { country: "Armenia", limit: 0.0 },
  { country: "Australia", limit: 0.05 },
  { country: "Austria", limit: 0.05 },
  { country: "Azerbaijan", limit: 0.0 },
  { country: "Bahamas", limit: 0.08 },
  { country: "Bahrain", limit: 0.0 },
  { country: "Bangladesh", limit: 0.0 },
  { country: "Barbados", limit: 0.08 },
  { country: "Belarus", limit: 0.03 },
  { country: "Belgium", limit: 0.05 },
  { country: "Belize", limit: 0.08 },
  { country: "Benin", limit: 0.05 },
  { country: "Bhutan", limit: 0.08 },
  { country: "Bolivia", limit: 0.05 },
  { country: "Bosnia and Herzegovina", limit: 0.03 },
  { country: "Botswana", limit: 0.08 },
  { country: "Brazil", limit: 0.0 },
  { country: "Brunei", limit: 0.0 },
  { country: "Bulgaria", limit: 0.05 },
  { country: "Burkina Faso", limit: 0.08 },
  { country: "Burundi", limit: 0.08 },
  { country: "Cabo Verde", limit: 0.05 },
  { country: "Cambodia", limit: 0.0 },
  { country: "Cameroon", limit: 0.08 },
  { country: "Canada", limit: 0.08 },
  { country: "Central African Republic", limit: 0.08 },
  { country: "Chad", limit: 0.08 },
  { country: "Chile", limit: 0.03 },
  { country: "China", limit: 0.02 },
  { country: "Colombia", limit: 0.04 },
  { country: "Comoros", limit: 0.08 },
  { country: "Congo (Brazzaville)", limit: 0.08 },
  { country: "Congo (Kinshasa)", limit: 0.08 },
  { country: "Costa Rica", limit: 0.05 },
  { country: "Croatia", limit: 0.05 },
  { country: "Cuba", limit: 0.05 },
  { country: "Cyprus", limit: 0.05 },
  { country: "Czech Republic", limit: 0.0 },
  { country: "Denmark", limit: 0.05 },
  { country: "Djibouti", limit: 0.0 },
  { country: "Dominica", limit: 0.08 },
  { country: "Dominican Republic", limit: 0.05 },
  { country: "Ecuador", limit: 0.01 },
  { country: "Egypt", limit: 0.0 },
  { country: "El Salvador", limit: 0.05 },
  { country: "Equatorial Guinea", limit: 0.08 },
  { country: "Eritrea", limit: 0.08 },
  { country: "Estonia", limit: 0.02 },
  { country: "Eswatini", limit: 0.08 },
  { country: "Ethiopia", limit: 0.0 },
  { country: "Fiji", limit: 0.08 },
  { country: "Finland", limit: 0.05 },
  { country: "France", limit: 0.05 },
  { country: "Gabon", limit: 0.08 },
  { country: "Gambia", limit: 100.0 },
  { country: "Georgia", limit: 0.03 },
  { country: "Germany", limit: 0.05 },
  { country: "Ghana", limit: 0.08 },
  { country: "Greece", limit: 0.05 },
  { country: "Grenada", limit: 0.08 },
  { country: "Guatemala", limit: 0.05 },
  { country: "Guinea", limit: 0.08 },
  { country: "Guinea-Bissau", limit: 100.0 },
  { country: "Guyana", limit: 0.08 },
  { country: "Haiti", limit: 0.08 },
  { country: "Honduras", limit: 0.07 },
  { country: "Hungary", limit: 0.0 },
  { country: "Iceland", limit: 0.02 },
  { country: "India", limit: 0.03 },
  { country: "Indonesia", limit: 0.0 },
  { country: "Iran", limit: 0.0 },
  { country: "Iraq", limit: 0.0 },
  { country: "Ireland", limit: 0.05 },
  { country: "Israel", limit: 0.05 },
  { country: "Italy", limit: 0.05 },
  { country: "Jamaica", limit: 0.08 },
  { country: "Japan", limit: 0.03 },
  { country: "Jordan", limit: 0.0 },
  { country: "Kazakhstan", limit: 0.0 },
  { country: "Kenya", limit: 0.08 },
  { country: "Kiribati", limit: 0.08 },
  { country: "Kuwait", limit: 0.0 },
  { country: "Kyrgyzstan", limit: 0.0 },
  { country: "Laos", limit: 0.08 },
  { country: "Latvia", limit: 0.05 },
  { country: "Lebanon", limit: 0.02 },
  { country: "Lesotho", limit: 0.08 },
  { country: "Liberia", limit: 0.08 },
  { country: "Libya", limit: 0.0 },
  { country: "Liechtenstein", limit: 0.08 },
  { country: "Lithuania", limit: 0.04 },
  { country: "Luxembourg", limit: 0.05 },
  { country: "Madagascar", limit: 0.08 },
  { country: "Malawi", limit: 0.08 },
  { country: "Malaysia", limit: 0.08 },
  { country: "Maldives", limit: 0.0 },
  { country: "Mali", limit: 0.08 },
  { country: "Malta", limit: 0.05 },
  { country: "Marshall Islands", limit: 0.08 },
  { country: "Mauritania", limit: 0.0 },
  { country: "Mauritius", limit: 0.05 },
  { country: "Mexico", limit: 0.08 },
  { country: "Micronesia", limit: 0.08 },
  { country: "Moldova", limit: 0.03 },
  { country: "Monaco", limit: 0.05 },
  { country: "Mongolia", limit: 0.0 },
  { country: "Montenegro", limit: 0.03 },
  { country: "Morocco", limit: 0.0 },
  { country: "Mozambique", limit: 0.05 },
  { country: "Myanmar", limit: 0.08 },
  { country: "Namibia", limit: 0.05 },
  { country: "Nauru", limit: 0.08 },
  { country: "Nepal", limit: 0.05 },
  { country: "Netherlands", limit: 0.05 },
  { country: "New Zealand", limit: 0.05 },
  { country: "Nicaragua", limit: 0.05 },
  { country: "Niger", limit: 100.0 },
  { country: "Nigeria", limit: 0.05 },
  { country: "North Korea", limit: 0.0 },
  { country: "North Macedonia", limit: 0.05 },
  { country: "Norway", limit: 0.02 },
  { country: "Oman", limit: 0.0 },
  { country: "Pakistan", limit: 0.0 },
  { country: "Palau", limit: 0.08 },
  { country: "Panama", limit: 0.08 },
  { country: "Papua New Guinea", limit: 0.08 },
  { country: "Paraguay", limit: 0.05 },
  { country: "Peru", limit: 0.05 },
  { country: "Philippines", limit: 0.05 },
  { country: "Poland", limit: 0.02 },
  { country: "Portugal", limit: 0.05 },
  { country: "Qatar", limit: 0.0 },
  { country: "Romania", limit: 0.0 },
  { country: "Russia", limit: 0.0 },
  { country: "Rwanda", limit: 0.08 },
  { country: "Saint Kitts and Nevis", limit: 0.08 },
  { country: "Saint Lucia", limit: 0.08 },
  { country: "Saint Vincent and the Grenadines", limit: 0.08 },
  { country: "Samoa", limit: 0.08 },
  { country: "San Marino", limit: 0.05 },
  { country: "Sao Tome and Principe", limit: 0.08 },
  { country: "Saudi Arabia", limit: 0.0 },
  { country: "Senegal", limit: 0.08 },
  { country: "Serbia", limit: 0.03 },
  { country: "Seychelles", limit: 0.08 },
  { country: "Sierra Leone", limit: 0.08 },
  { country: "Singapore", limit: 0.08 },
  { country: "Slovakia", limit: 0.0 },
  { country: "Slovenia", limit: 0.05 },
  { country: "Solomon Islands", limit: 0.08 },
  { country: "Somalia", limit: 0.0 },
  { country: "South Africa", limit: 0.05 },
  { country: "South Korea", limit: 0.03 },
  { country: "South Sudan", limit: 0.08 },
  { country: "Spain", limit: 0.05 },
  { country: "Sri Lanka", limit: 0.08 },
  { country: "Sudan", limit: 0.0 },
  { country: "Suriname", limit: 0.08 },
  { country: "Sweden", limit: 0.02 },
  { country: "Switzerland", limit: 0.05 },
  { country: "Syria", limit: 0.0 },
  { country: "Taiwan", limit: 0.03 },
  { country: "Tajikistan", limit: 0.0 },
  { country: "Tanzania", limit: 0.08 },
  { country: "Thailand", limit: 0.05 },
  { country: "Timor-Leste", limit: 0.08 },
  { country: "Togo", limit: 0.08 },
  { country: "Tonga", limit: 0.08 },
  { country: "Trinidad and Tobago", limit: 0.08 },
  { country: "Tunisia", limit: 0.03 },
  { country: "Turkey", limit: 0.05 },
  { country: "Turkmenistan", limit: 0.0 },
  { country: "Tuvalu", limit: 0.08 },
  { country: "Uganda", limit: 0.08 },
  { country: "Ukraine", limit: 0.02 },
  { country: "United Arab Emirates", limit: 0.0 },
  { country: "United Kingdom", limit: 0.08 },
  { country: "United States", limit: 0.08 },
  { country: "Uruguay", limit: 0.03 },
  { country: "Uzbekistan", limit: 0.0 },
  { country: "Vanuatu", limit: 0.08 },
  { country: "Vatican City", limit: 0.0 },
  { country: "Venezuela", limit: 0.05 },
  { country: "Vietnam", limit: 0.0 },
  { country: "Yemen", limit: 0.0 },
  { country: "Zambia", limit: 0.08 },
  { country: "Zimbabwe", limit: 0.08 },
];
